Document: v4l2loopback
Title: Debian v4l2loopback Manual
Author: <insert document author here>
Abstract: This manual describes what v4l2loopback is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/v4l2loopback/v4l2loopback.sgml.gz

Format: postscript
Files: /usr/share/doc/v4l2loopback/v4l2loopback.ps.gz

Format: text
Files: /usr/share/doc/v4l2loopback/v4l2loopback.text.gz

Format: HTML
Index: /usr/share/doc/v4l2loopback/html/index.html
Files: /usr/share/doc/v4l2loopback/html/*.html
